### ISSUE TITLE
task checklist from Steve-Miwa meeting about template generator

### ISSUE THREAD

**Issue by sformel-usgs** [FAIR-eDNA/FAIRe-ator#8]
- [ ] check that all packages are installed
- [ ] ensure that readme is using UTC time
- [ ] filenaming structure is evolving, update as needed
- [ ] sampleMetadata, collection to extraction
- [ ] accommodate new data type: `experimentMetadata`, PCR to Sequencing
- [ ] decide input endpoint (probably github)
- [ ] add code to generate columns from `studyMetadata_user` and `sampleMetadata_user`
- [ ] some sections are common to both `detection_type` but aren't being included in both [sample_collection, sample_storage, sample_preparation, quality_assurance, sample_relations, nucleic_acid_extraction, envrionment]
- [ ] make alias for 'detection type' i.e. 'qPCR' along with 'Targeted taxon detection`
- [ ] transpose orientation of `studyMetadata` in output, currently vertical, should be horizontal.
- [ ] color of requirement level isn't matching actual term values
- [ ] output should have (1) project file, with `readme`, `studyMetdata`, `sampleMetadata`, and `experimentMetadata` [multitaxa only]
- [ ] dnaSeqData should have target_gene + libraryID in filename.
- [ ] user manually changes 'libraryID' after template generation, can we automate this instead? Library == pooled libraries, so it should be updated to `seq_run_id`
- [ ] order of terms should remain as they are in the template: some people want to see mandatory first, others want to see native order
